In [1]:
import numpy as np
a=np.arange(1, 7).reshape((2, 3))
b=np.arange(7, 13).reshape((2, 3))
c=np.arange(13, 19).reshape((2, 3))
d=np.arange(19, 25).reshape((2, 3))

In [2]:
np.stack((a, b, c, d), axis=0)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [3]:
a = np.arange(2*3*4).reshape(2,3,4)
print(a)
print(a.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [4]:
np.stack(a[1], axis=0)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [5]:
import numpy as np
import torch

a = np.array([1, 2, 3])
t = torch.from_numpy(a)

a[0] = 10
print(t)  # tensor([10,  2,  3], dtype=torch.int32)

tensor([10,  2,  3])


In [6]:
a[0] = 2
print(t) 

tensor([2, 2, 3])


In [9]:
import numpy as np
import torch

a = np.array([1, 2, 3])
t = torch.from_numpy(a)

print(t)
print(a)

tensor([1, 2, 3])
[1 2 3]


In [22]:
del a

In [24]:
import torch
import torch.nn.functional as F

x = torch.tensor([[1, 2], [3, 4]])
padded = F.pad(x, (0, 0, 0, 1))
print(padded)

tensor([[1, 2],
        [3, 4],
        [0, 0]])
